
name: CI - Rodar Testes e Publicar Relatório

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  rodar-testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Instalar dependências
        run: npm ci

      - name: Executar os testes (modo headless)
        run: npx cypress run
